### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by josemolmomillan** [coletivoEITA/matrix-react-sdk#1]
https://github.com/coletivoEITA/matrix-react-sdk/blob/3f83ace2b7ddc53183339b4bd142ac4335b5eaa2/src/components/structures/MatrixChat.js#L1645

I had to add }, previous to this line

**Comment by dtygel** [comment]
Thanks for alerting. Fixed https://github.com/coletivoEITA/matrix-react-sdk/commit/8e477883fd6d991d0af7a754989d688779c41046
